In [1]:
from sklearn import datasets
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

- n_samples：控制生成的样本点的个数
- n_features：控制与类别有关的自变量的维数
- n_classes：控制生成的分类数据类别的数量

In [ ]:
X, y = make_classification(n_samples=10000,   # 样本个数
                               n_features=25,              # 特征个数
                               n_informative=3,            # 有效特征个数
                               n_redundant=2,             # 冗余特征个数（有效特征的随机组合）
                               n_repeated=0,              # 重复特征个数（有效特征和冗余特征的随机组合）
                               n_classes=3,                # 样本类别
                               n_clusters_per_class=1, # 簇的个数
                               random_state=0)

In [3]:
X,y = datasets.make_classification(n_samples=1000,
                                   n_features=20, 
                                   n_informative=2, 
                                   n_redundant=2, 
                                   n_repeated=0, 
                                   n_classes=2, 
                                   n_clusters_per_class=2, 
                                   weights=None, 
                                   flip_y=0.01, 
                                   class_sep=1.0,
                                   hypercube=True, 
                                   shift=0.0, 
                                   scale=1.0, 
                                   shuffle=True, 
                                   random_state=None)


df = pd.DataFrame(data = X)
df['label'] = y
df.head()

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,label
0,0.571286,-0.085450,0.355155,0.734452,1.648437,-0.136311,-0.578497,0.653885,-0.894738,-1.363650,...,-2.298573,0.312862,0.581067,1.268788,0.143708,-0.225781,-0.423219,-1.168203,0.227848,0
1,-0.617478,-0.672981,0.663991,0.308884,0.021061,-1.375040,1.247527,-1.380758,-0.863969,-0.322900,...,-0.712112,1.171076,-0.421630,0.492102,-0.075303,1.594215,-0.463386,0.272802,-1.635234,1
2,-0.059268,0.214616,0.672041,2.173878,-1.407727,1.719997,-0.259593,-0.422312,-1.347722,-0.084646,...,-0.258393,-0.285867,0.811635,-0.258731,-0.396034,1.500731,-0.578565,-0.728790,0.753837,0
3,-0.223579,-1.042472,1.036488,1.647062,0.077136,1.708083,-1.232806,1.115886,-1.301217,-0.035050,...,0.209972,1.941887,0.660301,-0.963265,-1.231486,0.408379,0.574798,-0.514163,-2.193897,1
4,-1.192304,0.336891,1.255565,0.484758,1.254486,0.210933,-0.764251,0.625484,0.091341,-1.420996,...,-0.627982,-0.439074,-0.508489,-0.601134,-0.790390,-1.235775,-0.581166,-1.214794,1.208954,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
0        1000 non-null float64
1        1000 non-null float64
2        1000 non-null float64
3        1000 non-null float64
4        1000 non-null float64
5        1000 non-null float64
6        1000 non-null float64
7        1000 non-null float64
8        1000 non-null float64
9        1000 non-null float64
10       1000 non-null float64
11       1000 non-null float64
12       1000 non-null float64
13       1000 non-null float64
14       1000 non-null float64
15       1000 non-null float64
16       1000 non-null float64
17       1000 non-null float64
18       1000 non-null float64
19       1000 non-null float64
label    1000 non-null int64
dtypes: float64(20), int64(1)
memory usage: 164.1 KB

In [5]:
df.describe()

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,label
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,...,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,-0.005955,-0.003692,0.005624,-0.001061,0.009491,-0.001530,-0.037427,-0.000787,-0.020128,0.051881,...,-0.004265,0.010282,0.044409,0.054572,-0.064993,-0.029555,-0.002823,-0.026766,0.001262,0.502000
std,0.983206,0.639425,0.963767,1.015479,0.999644,1.008631,0.952764,0.982702,0.970959,1.002780,...,1.007620,1.213582,0.980421,0.956863,1.022150,0.992228,0.976831,1.195828,1.373505,0.500246
min,-3.387322,-2.187279,-3.100747,-2.934561,-3.794434,-2.892674,-2.798121,-3.879588,-3.128872,-3.982528,...,-3.005843,-3.242316,-2.901275,-3.029195,-3.067789,-3.208858,-4.032076,-2.982076,-4.310454,0.000000
25%,-0.643191,-0.487807,-0.647164,-0.683998,-0.674296,-0.670616,-0.664781,-0.667524,-0.646753,-0.604097,...,-0.670502,-0.955620,-0.608783,-0.546730,-0.768389,-0.695275,-0.653167,-1.003398,-1.027154,0.000000
50%,-0.026995,0.146630,-0.015035,-0.034130,0.031982,-0.009114,-0.064947,-0.021426,-0.053651,0.046847,...,0.009367,-0.220021,0.006741,0.077985,-0.054020,-0.053507,-0.019312,-0.246491,0.366280,1.000000
75%,0.673233,0.507184,0.674498,0.683873,0.691584,0.629210,0.618190,0.701333,0.578990,0.731097,...,0.682813,0.952860,0.661835,0.670732,0.626466,0.649625,0.671047,0.988718,1.070032,1.000000
max,2.765606,1.504883,4.319774,3.279571,3.374391,3.229331,3.936678,3.113618,3.291505,3.060419,...,4.028730,4.184748,3.347151,3.184923,3.072724,3.271000,3.116937,3.959193,2.897921,1.000000